### ISSUE TITLE
Get provision signed error but setting is ok 

### ISSUE THREAD

**Issue by walter211** [spritefly/ios-builder#1]
`Check dependencies
Code Signing Error: Lottie_iOS has conflicting provisioning settings. Lottie_iOS is automatically signed, but provisioning profile 00000000-0000-0000-0000-000000000000 has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the project editor.`

![123](https://user-images.githubusercontent.com/2074640/35551733-6cd3ad48-05cb-11e8-8f54-61fb194cdc74.png)

===== updated 20180130 ====

Commented the provision setting in scirpt，shows another one 
`
/node_modules/lottie-react-native/lib/ios/LottieReactNative/LRNContainerView.h:19:9: fatal error: 
      'Lottie/Lottie.h' file not found
#import <Lottie/Lottie.h>
        ^~~~~~~~~~~~~~~~~
1 error generated.`

**Comment by spritefly** [comment]
if you use automatic signing, you should remove the -xcconfig and -exportOptionsPlist options from the build script, as following:
```bash
# archive
xcodebuild archive -project ${PROJECT_NAME}.xcodeproj \
                   -scheme ${SCHEME_NAME} \
                   -destination generic/platform=iOS \
                   -archivePath bin/${PROJECT_NAME}.xcarchive \
                   || failed "xcodebuild archive"
# export ipa
xcodebuild -exportArchive -archivePath bin/${PROJECT_NAME}.xcarchive \
                          -exportPath bin \
                          -verbose \
                          || failed "xcodebuild export archive"
```

**Comment by spritefly** [comment]
This error unrelated with the build script, you should inspect the include header settings
> Commented the provision setting in scirpt，shows another one
> /node_modules/lottie-react-native/lib/ios/LottieReactNative/LRNContainerView.h:19:9: fatal error: 'Lottie/Lottie.h' file not found #import <Lottie/Lottie.h> ^~~~~~~~~~~~~~~~~ 1 error generated.
